apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halan-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: halan
            port:
              number: 80
---
kind: Service
apiVersion: v1
metadata:
  name: halan
spec:
  selector:
    app: halan
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: halan
  template:
    metadata:
      labels:
        app: halan
    spec:
      containers:
        - name: halan
          image: afayez14/ips-api
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: halan-config-map
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-release-postgresql
                  key: postgresql-password
            
          ports:
            - containerPort: 5000
              protocol: TCP