#!/usr/bin/env bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

: "${HELM_RELEASE_NAME:=pg-release}"
: "${CLUSTER_NAME:=halan-cluster}"
: "${APP_NAME:=halan}"
: "${INGRESS_HTTP_PORT:=80}"

k3d cluster create \
    -p "${INGRESS_HTTP_PORT}:80@loadbalancer" \
    --agents 2 \
    "${CLUSTER_NAME}"


# deploy postgres 
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install -f "${SCRIPT_DIR}/values.yml" "${HELM_RELEASE_NAME}" bitnami/postgresql \
    --set postgresqlPassword=secretAdminPassword
    

: "${DB_USER:=postgres}"
: "${DB_HOST:=$HELM_RELEASE_NAME-postgresql}"
: "${DB_PORT:=5432}"
: "${DB_NAME:=postgres}"

cat <<EOF >"${SCRIPT_DIR}/configmap.yml"
apiVersion: v1
kind: ConfigMap
metadata:
  name: halan-config-map
  namespace: default
data:
  DB_USER: "${DB_USER}"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
EOF

kubectl create -f "${SCRIPT_DIR}/configmap.yml"
kubectl apply -f "${SCRIPT_DIR}"/api.yml
