version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev-db
      - FLASK_APP=api.py
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data: